### ISSUE TITLE
Bug in evaluation code?

### ISSUE THREAD

**Issue by lugiavn** [yalesong/tvsum50#1] opened 2019-01-28 19:45 UTC
Hey it has been a while and doesn't look like this has been fixed? I'm checking back to see if anybody else has released new evaluation codes?

**Description of the bug**: when run the provided code, random performance looks like this:
![screenshot from 2019-01-28 14 22 47](https://user-images.githubusercontent.com/1468668/51861548-89cbf100-230a-11e9-92a9-024e38cd1024.png)

But if we change random segmentation to a more advanced level such as this:
![screenshot from 2019-01-28 14 29 11](https://user-images.githubusercontent.com/1468668/51861639-bd0e8000-230a-11e9-8289-9a0cb17e8ae3.png)
Then random performance is now at:
![screenshot from 2019-01-28 14 28 58](https://user-images.githubusercontent.com/1468668/51861669-d0215000-230a-11e9-81a8-b9a14a9d7d75.png)
Wow that is close to state of the art!

Lets take it further and use the ultimate segmentation strategy like this:
![screenshot from 2019-01-28 14 34 36](https://user-images.githubusercontent.com/1468668/51861744-f6df8680-230a-11e9-9489-6d8ba2d33ae5.png)

Then run evaluation code:
![screenshot from 2019-01-28 14 35 14](https://user-images.githubusercontent.com/1468668/51861764-065ecf80-230b-11e9-9637-f06b4e5b2a97.png)
Perfect performance no matter what method it is!!!

**Comment by yalesong** [comment] 2019-02-05 03:01
Hey, thanks for this! Let me get back on this after the CVPR rebuttals next week.

**Comment by yalesong** [comment] 2019-02-20 18:08
I can confirm this issue can be reproduced. It happens because the variable `segment_results` is shared between user scores and predicted scores when solving knapsack to produce the resulting summaries. This can cause weird behaviors when `segment_results` contain unrealistic shot boundary information: one can segment the video into only a few chunks (such as the two scenarios you've tested) and get an arbitrarily high performance regardless of per-frame scores. 

For example, in the third scenario above, the predefined shot boundaries of `[1, 5, 10, 2000]` will produce four segments. The first segment contains a single frame [1:1], the second contains 4 frames [2:5], the third contains 5 frames [6:10], and the fourth contains all the rest in a given video. In other words, the last chunk will be the same as input video minus the first 10 frames (!). At 15% budget, knapsack will always return the first three segments as the resulting summary regardless of what per-frame scores are used. This guarantees perfect performance no matter what method we use.

The user annotations are made at a fixed interval of 2 seconds (60 frames). The demo eval script uses random shot frames with lengths roughly equal to 2 seconds, for both user scores and predicted scores; hence the expected behavior. If one wants to use their custom shot boundary information, the GT summaries will have to be computed using the fixed interval of 2 seconds.

I will leave this issue open until I provide an updated demo script fixing this issue. Thanks for reporting the issue!

**Comment by lugiavn** [comment] 2019-02-20 18:45
Okay thanks.
But there is the hidden "bug" that you haven't found. It causes the performance to increase in my 1st and 2nd examples. Random performance should have been ~15% or something, 30% is fishy and indicating a bug. Like, if you really think about it, how can randomly choosing 15% of frames can have a performance of 30% or even 50%?

Lets look at it this way: what if all frames in the video has the same scores?
All frames are the same, no one is more important than the other.
In this case, each segment score = avg its frame score = the same?
Then the nature of knapsack (optimizing for sum, not avg, given a budget) will always pick shorter segments. Is this behavior intended?

As the result, in my 1st example (even with different frame scores), both GT and random are biased toward short segments, hence that inflates the overlap between them (from ~15% or something to 30%).

**Comment by yalesong** [comment] 2019-02-20 20:02
The "hidden bug" is also caused by the same problem I described above. I've pushed an updated version of the demo eval script with [a bug fix](https://github.com/yalesong/tvsum/blob/master/matlab/script_evaluate_result.m#L82-L84). You're correct that random perf should be around 15%; the new demo script produces around 15% performance using random score prediction. 

I am closing this issue but feel free to re-open / create another if you find further issues.

**Closed as completed by yalesong** 2019-02-20 20:02 UTC
